runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main
api_version: 1
threadsafe: true

runtime_config:
  python_version: 2

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app

skip_files:
- .git/
